name: Deploy Frontend to S3

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias y build
        run: |
          npm install
          npm run build

      - name: Deploy a S3 y limpiar cache CloudFront
        run: |
          # Cambié el nombre del bucket S3 por frontend-juego-trivial
          aws s3 sync build/ s3://frontend-juego-trivial --delete
          
          # El ID de la distribución de CloudFront sigue siendo frontend-juego-trivial
          aws cloudfront create-invalidation --distribution-id frontend-juego-trivial --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"

